import "../styles/globals.css"
import Header from "./components/Header"
import Head from "next/head"
import { useRouter } from "next/router"

function MyApp({ Component, pageProps }) {
	return (
		<div className="flex flex-col">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className="flex flex-1 min-h-screen">
				<Component {...pageProps} />
			</main>
		</div>
	)
}

export default MyApp
